### ISSUE TITLE
Fail to subscribe to system topic

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zbctl#29]
When I try to subscribe from the system topic

`./zbctl subscribe topic internal-system`

then I get the error

```
partitions not found
panic: Failed to open subscription

goroutine 1 [running]:
github.com/zeebe-io/zbctl/cmd.glob..func14(0xb92bc0, 0xc420081590, 0x1, 0x1)
	/home/camunda/workspace/zeebe-RELEASE-pipeline/gopath/src/github.com/zeebe-io/zbctl/cmd/topicSubscription.go:105 +0x70b
github.com/zeebe-io/zbctl/vendor/github.com/spf13/cobra.(*Command).execute(0xb92bc0, 0xc420081550, 0x1, 0x1, 0xb92bc0, 0xc420081550)
	/home/camunda/workspace/zeebe-RELEASE-pipeline/gopath/src/github.com/zeebe-io/zbctl/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/zeebe-io/zbctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb92560, 0xc4200b6690, 0x0, 0xb92de0)
	/home/camunda/workspace/zeebe-RELEASE-pipeline/gopath/src/github.com/zeebe-io/zbctl/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/zeebe-io/zbctl/vendor/github.com/spf13/cobra.(*Command).Execute(0xb92560, 0xc42007e058, 0x0)
	/home/camunda/workspace/zeebe-RELEASE-pipeline/gopath/src/github.com/zeebe-io/zbctl/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/zeebe-io/zbctl/cmd.Execute()
	/home/camunda/workspace/zeebe-RELEASE-pipeline/gopath/src/github.com/zeebe-io/zbctl/cmd/root.go:48 +0x2d
main.main()
	/home/camunda/workspace/zeebe-RELEASE-pipeline/gopath/src/github.com/zeebe-io/zbctl/main.go:20 +0x20
```

**Comment by menski** [comment]
I think it is currently not possible to subscribe to the system topic https://github.com/zeebe-io/zeebe/issues/423
